# Generated by Django 5.0.4 on 2024-05-03 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0002_alter_reserva_sala_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='reserva',
            name='tipo_de_reserva',
            field=models.CharField(choices=[('AUD', 'Auditorio'), ('CON', 'Sala de Conferencias'), ('AUL', 'Aula'), ('LAB', 'Laboratorio')], default='AUL', max_length=3),
        ),
    ]
